url: "https://github.com/ElliotReed" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/learning-lab-notes" # the subpath of your site, e.g. /blog
title: "Learning Lab Notes" # the name of your site, e.g. ACME Corp.
