# The Site Configuration

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Denver

title: "Learning Lab Notes" # the name of your site, e.g. ACME Corp.

url: "https://github.com/ElliotReed" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/learning-lab-notes" # the subpath of your site, e.g. /blog

collections:
  notes:
    output: true
    permalink: /:categories/:title

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - README.md
  - package*.json
